### ISSUE TITLE
Review black-list issues on build-fontmetadata script

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/gftools#16]
originally posted at:
* https://github.com/googlefonts/fontbakery/issues/783
* https://github.com/googlefonts/fontbakery/issues/1021
* https://github.com/googlefonts/fontbakery/issues/704

All blacklisted fonts on fontbakery-build-fontmetadata.py have issues with the OpenType hinting tables that trigger the check at https://github.com/felipesanches/fontbakery/blob/06945641497a642422a101d904420fda3eca9815/fontbakery-build-fontmetadata.py#L588-L607

See issue #704. I attempted to remove each of the blacklisted fonts in order to replicate the problem that originally caused them to be blacklisted. But instead all of those were auto-blacklisted by the all-or-nothing hinting tables criteria described at https://github.com/googlefonts/fontbakery/issues/705#issuecomment-244800828.

* * * 

@davelab6 edited this issue to consolidate tasks from the discussion below. 

- [ ] IOError: execution context too long (issue #703) - Padauk
- [ ] IOError: execution context too long (issue #703) - KumarOne

- [ ] ZeroDivisionError: float division by zero - AdobeBlank
- [ ] ZeroDivisionError: float division by zero - Phetsarath

- [ ] IOError: invalid reference ([reference](https://github.com/google/fonts/issues/132#issuecomment-244796023)) - Corben
- [ ] IOError: stack overflow on text_width, text_height = font.getsize(TEXT) - Rubik

**Comment by felipesanches** [comment]
to be done after merging #10

**Comment by HinTak** [comment]
The two float divisions by zero error are AFAIK not part of the two fonts, but part of fontbakery's python code. Already wrote to @davelab6 a while ago.

**Comment by davelab6** [comment]
In https://github.com/google/fonts/pull/1330 I think I spotted a problem where Marc said,

> We need the metadata.pb file regenerated with googlefonts/tools:bin/gftools-add-font.py@master

And in response I said (unfortunately ambiguously)

> Marc, why did you request this? Did a tool not pick it up?

(I was referring only to the metadata thing :) 

So, we regenerate a METADATA.pb file using the `add_font.py` script, then the `date-added` will change incorrectly, as demonstrated in the Barlow PR. 

I believe this was already corrected in this tool, which looks for an existing METADATA file and if found pulls in existing manual values.

This tool started life with Jeremie in 2009 when it generated JSON files, maintained by various fontbakery devs, and most recently was ported to the new protobuf format by Felipe. However when the GF eng team made the transition to protobufs, they wrote a new tool, which is the one Marc mentioned. 

So, we should probably port the things in this script that are not in `add_font.py` to it.

**Comment by simoncozens** [comment]
This tool is long gone.
